### ISSUE TITLE
D4Builds import failed :(

### ISSUE THREAD

**Issue by Dragoy** [josdemmers/Diablo4Companion#106]
![image](https://github.com/josdemmers/Diablo4Companion/assets/4968313/75e70bee-3f4d-438d-9ee7-ab60f5250651)

**Comment by josdemmers** [comment]
Working fine here, which build are you trying to import?

**Comment by Dragoy** [comment]
https://d4builds.gg/builds/a9166100-954d-4b4e-b2b3-1f5c2bf6ed80

**Comment by josdemmers** [comment]
Looks good.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/d206c5b3-70b4-4626-98d5-13dabd5c3758)

What did you enter? Make it's only the id: `a9166100-954d-4b4e-b2b3-1f5c2bf6ed80`

**Comment by Dragoy** [comment]
> Looks good. ![image](https://private-user-images.githubusercontent.com/8627157/333895227-d206c5b3-70b4-4626-98d5-13dabd5c3758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDE3ODgsIm5iZiI6MTcxNjc0MTQ4OCwicGF0aCI6Ii84NjI3MTU3LzMzMzg5NTIyNy1kMjA2YzViMy03MGI0LTQ2MjYtOThkNS0xM2RhYmQ1YzM3NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMTYzODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDNhNmJkZDk4MjI4YzVjNjc2ZmRkNWEwM2FjMWIwMzQ2NzE2YmRmNWM0MzcyOTIzOGVlNWI0M2ViMWRhOTRmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ld1RNhl5LYfzUvHFj8-QZ5UCT2psZ0CN70ZVtu0w3MQ)
> 
> What did you enter? Make sure it's only the id: `a9166100-954d-4b4e-b2b3-1f5c2bf6ed80`

That's right, I checked again, it's not working again.

**Comment by josdemmers** [comment]
Does it happen with every d4build you try?
And could you add your `\Logging\Diablo4Companion.log' file? Maybe it contains some useful info

**Comment by jojoel** [comment]
`2024-05-29 19:44:37.1999|ERROR|D4Companion.Services.BuildsManagerD4Builds|DownloadD4BuildsBuild (4c364427-65c5-4749-ba9b-c86260afa515)
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 118
Current browser version is 125.0.6422.112 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at D4Companion.Services.BuildsManagerD4Builds.InitSelenium()
   at D4Companion.Services.BuildsManagerD4Builds.DownloadD4BuildsBuild(String buildIdD4Builds)`

Error about chrome version

**Comment by josdemmers** [comment]
@jojoel Thank you for the logging. I'll update the Chrome dependency in the next version.

**Comment by josdemmers** [comment]
@Dragoy @jojoel 
Can you give v3.4.7.0 a try and let me know if that works for you.

**Comment by jojoel** [comment]
`2024-05-30 17:42:27.8826|INFO|D4Companion.ViewModels.MainWindowViewModel|Diablo IV Companion v3.4.7.0
2024-05-30 17:42:27.8826|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-05-30 17:42:35.6661|ERROR|D4Companion.Services.BuildsManagerD4Builds|DownloadD4BuildsBuild (ef414fbd-81cd-49d1-9c8d-4938b278e2ee)
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 118
Current browser version is 125.0.6422.113 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at D4Companion.Services.BuildsManagerD4Builds.InitSelenium()
   at D4Companion.Services.BuildsManagerD4Builds.DownloadD4BuildsBuild(String buildIdD4Builds)`

it still error with new dowload or update from old version

**Comment by jojoel** [comment]
> ```batchfile
> selenium-manager --browser chrome --debug
> ```

It work, thanks.
